'use client'
export const dynamic='force-dynamic'
import {FormEvent,useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,ClipboardList,TrendingUp} from 'lucide-react'
import {createClient} from '../../lib/supabase/client'
export default function MeusSimulados(){
 const [s,setS]=useState<any>(null),[available,setAvailable]=useState<any[]>([]),[evolution,setEvolution]=useState<any[]>([]),[open,setOpen]=useState<string|null>(null),[msg,setMsg]=useState('')
 async function load(client=s){if(!client)return;const {data:{user}}=await client.auth.getUser();if(!user)return;const {data:en}=await client.from('enrollments').select('class_id').eq('student_id',user.id).eq('status','active');const ids=(en||[]).map((x:any)=>x.class_id);const [a,b]=await Promise.all([ids.length?client.from('simulations').select('id,name,simulation_date,total_questions,simulation_results!left(total_correct,essay_score)').in('class_id',ids).eq('active',true).order('simulation_date',{ascending:false}):Promise.resolve({data:[]}),client.rpc('my_simulation_evolution')]);setAvailable(a.data||[]);setEvolution(b.data||[])}
 useEffect(()=>{const client=createClient();setS(client);load(client)},[])
 async function save(id:string,e:FormEvent<HTMLFormElement>){e.preventDefault();if(!s)return;const fd=new FormData(e.currentTarget);const {error}=await s.rpc('save_simulation_result',{p_simulation_id:id,p_total_correct:Number(fd.get('correct')),p_essay_score:fd.get('essay')?Number(fd.get('essay')):null});setMsg(error?'Não foi possível salvar o resultado.':'Resultado salvo. Sua evolução foi atualizada.');if(!error){setOpen(null);load()}}
 return <main className="studentPage"><div className="studentShell"><Link href="/meu-painel" className="back"><ArrowLeft size={17}/> Meu painel</Link><span className="eyebrow">AVALIAÇÕES</span><h1>Meus simulados</h1><p className="muted">Registre seus resultados e acompanhe sua evolução ao longo da preparação.</p>{msg&&<div className="formMessage">{msg}</div>}
 <section className="performanceBox"><div className="sectionTitle"><div><TrendingUp/><div><span className="eyebrow">EVOLUÇÃO</span><h2>Histórico de desempenho</h2></div></div></div><div className="evolutionRow">{evolution.map((x:any)=><article key={x.simulation_id}><span>{new Date(x.simulation_date+'T00:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span><strong>{x.percentage}%</strong><small>{x.total_correct}/{x.total_questions} acertos</small></article>)}{!evolution.length&&<p className="emptyTiny">Seu gráfico de evolução começará após o primeiro resultado.</p>}</div></section>
 <div className="simulationStudentList">{available.map((x:any)=>{const r=x.simulation_results?.[0];return <article key={x.id}><div><ClipboardList/><div><strong>{x.name}</strong><span>{new Date(x.simulation_date+'T00:00:00').toLocaleDateString('pt-BR')} · {x.total_questions} questões</span></div></div><button onClick={()=>setOpen(open===x.id?null:x.id)}>{r?'Atualizar resultado':'Lançar resultado'}</button>{open===x.id&&<form onSubmit={e=>save(x.id,e)}><label>Acertos<input name="correct" required type="number" min="0" max={x.total_questions} defaultValue={r?.total_correct??''}/></label><label>Nota de redação <small>(opcional)</small><input name="essay" type="number" min="0" step=".01" defaultValue={r?.essay_score??''}/></label><button className="saveBtn">Salvar resultado</button></form>}</article>})}</div></div></main>
}