'use client'

export const dynamic = 'force-dynamic'
import {FormEvent,useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,Clock3,Plus} from 'lucide-react'
import {createClient} from '../../../../lib/supabase/client'
const days=['','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo']
export default function Grade({params}:{params:{id:string}}){const [s,setS]=useState<any>(null);const [subs,setSubs]=useState<any[]>([]);const [teachers,setTeachers]=useState<any[]>([]);const [slots,setSlots]=useState<any[]>([]);const [f,setF]=useState({weekday:'1',slot_order:'1',starts_at:'18:20',ends_at:'19:00',subject_id:'',teacher_id:''});const [msg,setMsg]=useState('')
async function load(){if(!s)return;const [a,b,c]=await Promise.all([s.from('class_subjects').select('subject_id,subjects(name)').eq('class_id',params.id),s.from('profiles').select('id,full_name').eq('role','teacher').eq('active',true).order('full_name'),s.from('class_schedule_slots').select('*,subjects(name),profiles(full_name)').eq('class_id',params.id).order('weekday').order('slot_order')]);setSubs(a.data||[]);setTeachers(b.data||[]);setSlots(c.data||[])}
useEffect(()=>{const s=createClient();setS(s);load()},[])
async function submit(e:FormEvent){if(!s)return;e.preventDefault();const {error}=await s.rpc('upsert_schedule_slot',{p_class_id:params.id,p_weekday:Number(f.weekday),p_slot_order:Number(f.slot_order),p_starts_at:f.starts_at,p_ends_at:f.ends_at,p_subject_id:f.subject_id||null,p_teacher_id:f.teacher_id||null});setMsg(error?'Não foi possível salvar o horário.':'Horário salvo.');if(!error)load()}
const ch=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
return <main className="formPage"><div className="formWrap wide"><Link href={'/turmas/'+params.id} className="back"><ArrowLeft size={17}/> Voltar à turma</Link><span className="eyebrow">GRADE SEMANAL</span><h1>Horários da turma</h1><p className="muted">Monte o padrão semanal que servirá de base para o cronograma.</p><form className="scheduleForm" onSubmit={submit}><select value={f.weekday} onChange={e=>ch('weekday',e.target.value)}>{days.slice(1).map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select><input type="number" min="1" value={f.slot_order} onChange={e=>ch('slot_order',e.target.value)}/><input type="time" value={f.starts_at} onChange={e=>ch('starts_at',e.target.value)}/><input type="time" value={f.ends_at} onChange={e=>ch('ends_at',e.target.value)}/><select value={f.subject_id} onChange={e=>ch('subject_id',e.target.value)}><option value="">Disciplina</option>{subs.map((x:any)=><option key={x.subject_id} value={x.subject_id}>{x.subjects?.name}</option>)}</select><select value={f.teacher_id} onChange={e=>ch('teacher_id',e.target.value)}><option value="">Professor</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><button><Plus size={16}/> Salvar</button></form>{msg&&<div className="formMessage">{msg}</div>}<div className="scheduleDays">{days.slice(1,6).map((d,i)=><section key={d}><h2>{d}</h2>{slots.filter(x=>x.weekday===i+1).map(x=><div className="slot" key={x.id}><Clock3 size={15}/><strong>{String(x.starts_at).slice(0,5)}–{String(x.ends_at).slice(0,5)}</strong><span>{x.subjects?.name||'Sem disciplina'}</span><em>{x.profiles?.full_name||'Professor a definir'}</em></div>)}</section>)}</div></div></main>}
