'use client'
export const dynamic='force-dynamic'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,BookOpen,CheckCircle2,Clock3,PlayCircle} from 'lucide-react'
import {createClient} from '../../lib/supabase/client'
const methods=['Questões','Resumo','Revisão','Material','Flashcards','Outro']
export default function MinhasAulas(){
 const [s,setS]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[open,setOpen]=useState<string|null>(null),[msg,setMsg]=useState('')
 async function load(client=s){if(!client)return;const {data:{user}}=await client.auth.getUser();if(!user)return;const {data:en}=await client.from('enrollments').select('class_id').eq('student_id',user.id).eq('status','active');const ids=(en||[]).map((x:any)=>x.class_id);if(!ids.length){setRows([]);return}const {data}=await client.from('lessons').select('id,title,lesson_date,starts_at,delivery,subjects(name),lesson_tracking!left(attendance,consolidated,study_minutes,questions_done,correct_answers,study_method)').in('class_id',ids).order('lesson_date',{ascending:false}).limit(100);setRows(data||[])}
 useEffect(()=>{const client=createClient();setS(client);load(client)},[])
 async function save(id:string,e:any){e.preventDefault();if(!s)return;const fd=new FormData(e.currentTarget),q=Number(fd.get('questions')||0),c=Number(fd.get('correct')||0);if(c>q){setMsg('Os acertos não podem ser maiores que as questões.');return}const {error}=await s.rpc('update_my_lesson_progress',{p_lesson_id:id,p_attendance:fd.get('attendance'),p_consolidated:fd.get('consolidated')==='on',p_study_minutes:Number(fd.get('minutes')||0)||null,p_questions_done:q||null,p_correct_answers:c||null,p_study_method:fd.get('method')||null});setMsg(error?'Não foi possível salvar.':'Progresso salvo.');if(!error){setOpen(null);load()}}
 return <main className="studentPage"><div className="studentShell"><Link href="/meu-painel" className="back"><ArrowLeft size={17}/> Meu painel</Link><span className="eyebrow">MINHA PREPARAÇÃO</span><h1>Minhas aulas</h1><p className="muted">Acompanhe a aula e registre o que você fez depois dela.</p>{msg&&<div className="formMessage">{msg}</div>}<div className="lessonFeed">{rows.map((x:any)=>{const t=x.lesson_tracking?.[0];return <article key={x.id} className="lessonItem"><div className="lessonTop"><div className="lessonDate"><span>{new Date(x.lesson_date+'T00:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span><small>{String(x.starts_at).slice(0,5)}</small></div><div className="lessonInfo"><span className="rowStatus">{x.subjects?.name}</span><h2>{x.title}</h2><div className="lessonBadges"><span><PlayCircle/> {t?.attendance==='live'?'Ao vivo':t?.attendance==='recorded'?'Gravada':'Pendente'}</span><span><CheckCircle2/> {t?.consolidated?'Consolidada':'Aguardando estudo'}</span></div></div><button onClick={()=>setOpen(open===x.id?null:x.id)}>Registrar</button></div>{open===x.id&&<form className="progressForm" onSubmit={e=>save(x.id,e)}><label>Como assistiu?<select name="attendance" defaultValue={t?.attendance||'pending'}><option value="live">Ao vivo</option><option value="recorded">Gravada</option><option value="pending">Ainda não assisti</option></select></label><label>Método de estudo<select name="method" defaultValue={t?.study_method||''}><option value="">Não estudei ainda</option>{methods.map(m=><option key={m}>{m}</option>)}</select></label><label><Clock3/> Tempo estudado (min)<input name="minutes" type="number" min="0" defaultValue={t?.study_minutes||''}/></label><div className="grid2"><label>Questões<input name="questions" type="number" min="0" defaultValue={t?.questions_done||''}/></label><label>Acertos<input name="correct" type="number" min="0" defaultValue={t?.correct_answers||''}/></label></div><label className="checkLine"><input name="consolidated" type="checkbox" defaultChecked={t?.consolidated}/> Considero este conteúdo estudado/consolidado</label><button className="saveBtn">Salvar progresso</button></form>}</article>})}{!rows.length&&<div className="emptyState"><BookOpen/><h2>Nenhuma aula disponível</h2><p>Quando sua turma tiver aulas cadastradas, elas aparecerão aqui.</p></div>}</div></div></main>
}