'use client'
export const dynamic='force-dynamic'
import {FormEvent,useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,CheckCircle2,Clock3,XCircle} from 'lucide-react'
import {createClient} from '../../../../lib/supabase/client'
export default function RegistroAulas({params}:{params:{id:string}}){
 const [s,setS]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[open,setOpen]=useState<string|null>(null),[msg,setMsg]=useState('')
 async function load(client=s){if(!client)return;const [a,b,c]=await Promise.all([client.from('lessons').select('*,subjects(name),profiles(full_name)').eq('class_id',params.id).order('lesson_date',{ascending:false}),client.from('class_subjects').select('subject_id,subjects(name)').eq('class_id',params.id),client.from('profiles').select('id,full_name').eq('role','teacher').eq('active',true).order('full_name')]);setRows(a.data||[]);setSubjects(b.data||[]);setTeachers(c.data||[])}
 useEffect(()=>{const client=createClient();setS(client);load(client)},[])
 async function confirm(id:string,e:FormEvent<HTMLFormElement>){e.preventDefault();if(!s)return;const fd=new FormData(e.currentTarget);const {error}=await s.rpc('confirm_delivered_lesson',{p_lesson_id:id,p_title:fd.get('title'),p_subject_id:fd.get('subject')||null,p_teacher_id:fd.get('teacher')||null,p_notes:fd.get('notes')||null});setMsg(error?'Não foi possível confirmar a aula.':'Aula confirmada. Agora ela entra no acompanhamento dos alunos.');if(!error){setOpen(null);load()}}
 async function cancel(id:string){if(!s)return;await s.rpc('cancel_scheduled_lesson',{p_lesson_id:id,p_notes:'Aula cancelada pela coordenação'});load()}
 return <main className="formPage"><div className="formWrap wide"><Link href={'/turmas/'+params.id} className="back"><ArrowLeft size={17}/> Voltar à turma</Link><span className="eyebrow">DIÁRIO DE AULA</span><h1>O que foi ministrado?</h1><p className="muted">A grade define quando e quem dá a aula. Aqui registramos somente o conteúdo que realmente aconteceu.</p>{msg&&<div className="formMessage">{msg}</div>}<div className="deliveredList">{rows.map((x:any)=><article key={x.id}><div className="deliveredHead"><div><span className={'lessonState '+x.status}>{x.status==='delivered'?'Ministrada':x.status==='cancelled'?'Cancelada':'Aguardando registro'}</span><strong>{new Date(x.lesson_date+'T00:00:00').toLocaleDateString('pt-BR')} · {String(x.starts_at).slice(0,5)}–{String(x.ends_at).slice(0,5)}</strong><small>{x.subjects?.name||'Disciplina a confirmar'} · {x.profiles?.full_name||'Professor a confirmar'}</small>{x.status==='delivered'&&<h3>{x.title}</h3>}</div>{x.status==='scheduled'&&<div className="lessonActions"><button onClick={()=>setOpen(open===x.id?null:x.id)}><CheckCircle2/> Registrar</button><button className="ghostDanger" onClick={()=>cancel(x.id)}><XCircle/> Cancelar</button></div>}</div>{open===x.id&&<form className="deliveredForm" onSubmit={e=>confirm(x.id,e)}><label>O que foi ministrado?<textarea name="title" required placeholder="Ex.: Função do 1º grau — conceito, exemplos e exercícios 1 a 12"/></label><div className="grid2"><label>Disciplina<select name="subject" defaultValue={x.subject_id||''}>{subjects.map((a:any)=><option key={a.subject_id} value={a.subject_id}>{a.subjects?.name}</option>)}</select></label><label>Professor<select name="teacher" defaultValue={x.teacher_id||''}><option value="">Selecione...</option>{teachers.map((t:any)=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label></div><label>Observações<textarea name="notes" placeholder="Opcional: ritmo da turma, conteúdo que continuará na próxima aula..."/></label><button className="saveBtn">Confirmar aula ministrada</button></form>}</article>)}</div></div></main>
}