'use client'
import { FormEvent,useEffect,useState } from 'react'
import Link from 'next/link'
import { ArrowLeft,CalendarPlus } from 'lucide-react'
import { createClient } from '../../../../../lib/supabase/client'

export default function NovaAula({params}:{params:{id:string}}){
 const s=createClient();const [subjects,setSubjects]=useState<any[]>([]);const [weeks,setWeeks]=useState<any[]>([]);const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false)
 const [f,setF]=useState({subject_id:'',academic_week_id:'',lesson_date:'',starts_at:'18:20',ends_at:'19:00',title:'',delivery:'live'})
 useEffect(()=>{Promise.all([s.from('class_subjects').select('subject_id,subjects(name)').eq('class_id',params.id),s.from('academic_weeks').select('*').eq('class_id',params.id).order('week_number')]).then(([a,b])=>{setSubjects(a.data||[]);setWeeks(b.data||[])})},[])
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);const {error}=await s.from('lessons').insert({...f,class_id:params.id});setMsg(error?'Não foi possível cadastrar a aula.':'Aula cadastrada com sucesso.');if(!error)setF(v=>({...v,title:'',lesson_date:''}));setSaving(false)}
 const ch=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
 return <main className="formPage"><div className="formWrap"><Link href={'/turmas/'+params.id} className="back"><ArrowLeft size={17}/> Voltar à turma</Link><div className="formHead"><div className="courseIcon"><CalendarPlus size={23}/></div><div><span className="eyebrow">CRONOGRAMA</span><h1>Nova aula</h1><p>Registre exatamente o conteúdo que será ministrado.</p></div></div>
 <form className="classForm" onSubmit={submit}><section><h2>Conteúdo da aula</h2><label>Disciplina<select required value={f.subject_id} onChange={e=>ch('subject_id',e.target.value)}><option value="">Selecione...</option>{subjects.map((x:any)=><option value={x.subject_id} key={x.subject_id}>{x.subjects?.name}</option>)}</select></label><label>Título / conteúdo<input required placeholder="Ex.: Função do 1º grau — exercícios" value={f.title} onChange={e=>ch('title',e.target.value)}/></label></section><section><h2>Quando acontecerá</h2><div className="grid2"><label>Semana<select value={f.academic_week_id} onChange={e=>ch('academic_week_id',e.target.value)}><option value="">Selecione...</option>{weeks.map((w:any)=><option value={w.id} key={w.id}>Semana {w.week_number}</option>)}</select></label><label>Data<input required type="date" value={f.lesson_date} onChange={e=>ch('lesson_date',e.target.value)}/></label></div><div className="grid2"><label>Início<input required type="time" value={f.starts_at} onChange={e=>ch('starts_at',e.target.value)}/></label><label>Fim<input required type="time" value={f.ends_at} onChange={e=>ch('ends_at',e.target.value)}/></label></div><label>Modalidade<select value={f.delivery} onChange={e=>ch('delivery',e.target.value)}><option value="live">Ao vivo</option><option value="recorded">Gravada</option><option value="hybrid">Ao vivo + gravação</option></select></label></section>{msg&&<div className="formMessage">{msg}</div>}<button className="saveBtn" disabled={saving}>{saving?'Salvando...':'Cadastrar aula'}</button></form></div></main>
}
